{{- if .Values.vpn.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openbao-vpn
  namespace: openbao
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: openbao-vpn
      namespace: openbao
      sectionName: http
  hostnames:
    - {{ .Values.vpn.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: openbao-api
          weight: 1
{{- end }}
